/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Arbitro_DAO;
import javax.swing.JOptionPane;

/**
 *
 * @author vinic
 */
public class CadastraArbitro extends javax.swing.JFrame {

    /**
     * Creates new form cadastraArbitro
     */
    public CadastraArbitro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        optRanking = new javax.swing.JComboBox<>();
        cadastraArbi = new javax.swing.JButton();
        btnVoltarMenu = new javax.swing.JButton();
        especiOpts = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nome");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(183, 70, 120, 16);

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        jPanel1.add(tfNome);
        tfNome.setBounds(180, 90, 220, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CADASTRO DE ARBITROS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 20, 610, 30);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ranking");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 120, 160, 16);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Especialidade");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 170, 220, 16);

        optRanking.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bronze", "prata", "ouro" }));
        optRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRankingActionPerformed(evt);
            }
        });
        jPanel1.add(optRanking);
        optRanking.setBounds(180, 140, 220, 22);

        cadastraArbi.setText("Cadastrar arbitro");
        cadastraArbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraArbiActionPerformed(evt);
            }
        });
        jPanel1.add(cadastraArbi);
        cadastraArbi.setBounds(180, 260, 230, 23);

        btnVoltarMenu.setText("Voltar");
        btnVoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltarMenu);
        btnVoltarMenu.setBounds(30, 360, 72, 23);

        especiOpts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Futebol", "Vôlei", "Basquete", "HandBall", "Tênis" }));
        especiOpts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especiOptsActionPerformed(evt);
            }
        });
        jPanel1.add(especiOpts);
        especiOpts.setBounds(180, 200, 220, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(609, 404));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void cadastraArbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraArbiActionPerformed
        String nome = tfNome.getText();
        String ranking = (String) optRanking.getSelectedItem();
        String especialidade = (String) especiOpts.getSelectedItem();
        
        if (!nome.isEmpty() && especialidade != null  && ranking != null) {
            
            Arbitro_DAO novoArbitro = new Arbitro_DAO(nome, especialidade, ranking);
            Arbitro_DAO.adicionarArbitro(novoArbitro);
            JOptionPane.showMessageDialog(null, "Arbitro cadastrado com sucesso");
            
            tfNome.setText("");
            especiOpts.setSelectedIndex(0);
            optRanking.setSelectedIndex(0);
        }else {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
        }
    }//GEN-LAST:event_cadastraArbiActionPerformed

    private void btnVoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarMenuActionPerformed
        new Menu_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarMenuActionPerformed

    private void optRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optRankingActionPerformed

    private void especiOptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especiOptsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especiOptsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastraArbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastraArbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastraArbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastraArbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastraArbitro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltarMenu;
    private javax.swing.JButton cadastraArbi;
    private javax.swing.JComboBox<String> especiOpts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> optRanking;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables
}
